apiVersion: v1
kind: PersistentVolume
metadata:
 name: book-library-mongo-pv
 labels:
  type: local
spec:
 storageClassName: generic
 capacity:
  storage: 256Mi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/var/lib/mongo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: book-library-mongo-pvc
spec:
 storageClassName: generic
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 256Mi