const FETCH_DATA = 'FETCH_DATA';
const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
const CREATE_BOOK = 'CREATE_BOOK';
const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
const CREATE_BOOK_FAIL = 'CREATE_BOOK_FAIL';
const UPDATE_BOOK = 'UPDATE_BOOK';
const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
const UPDATE_BOOK_FAIL = 'UPDATE_BOOK_FAIL';
const DELETE_BOOK = 'DELETE_BOOK';
const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
const DELETE_BOOK_FAIL = 'DELETE_BOOK_FAIL';
const CLEAR_BOOKS_ERROR = 'CLEAR_BOOKS_ERROR';

export {
  FETCH_DATA,
  FETCH_DATA_SUCCESS,
  FETCH_DATA_FAIL,
  CREATE_BOOK,
  CREATE_BOOK_SUCCESS,
  CREATE_BOOK_FAIL,
  UPDATE_BOOK,
  UPDATE_BOOK_SUCCESS,
  UPDATE_BOOK_FAIL,
  DELETE_BOOK,
  DELETE_BOOK_SUCCESS,
  DELETE_BOOK_FAIL,
  CLEAR_BOOKS_ERROR,
};
