const FETCH_BOOKS = 'FETCH_BOOKS';
const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL';
const CREATE_BOOK = 'CREATE_BOOK';
const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
const CREATE_BOOK_FAIL = 'CREATE_BOOK_FAIL';
const UPDATE_BOOK = 'UPDATE_BOOK';
const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
const UPDATE_BOOK_FAIL = 'UPDATE_BOOK_FAIL';
const DELETE_BOOK = 'DELETE_BOOK';
const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
const DELETE_BOOK_FAIL = 'DELETE_BOOK_FAIL';
const CLEAR_BOOKS_ERROR = 'CLEAR_BOOKS_ERROR';

export {
  FETCH_BOOKS,
  FETCH_BOOKS_SUCCESS,
  FETCH_BOOKS_FAIL,
  CREATE_BOOK,
  CREATE_BOOK_SUCCESS,
  CREATE_BOOK_FAIL,
  UPDATE_BOOK,
  UPDATE_BOOK_SUCCESS,
  UPDATE_BOOK_FAIL,
  DELETE_BOOK,
  DELETE_BOOK_SUCCESS,
  DELETE_BOOK_FAIL,
  CLEAR_BOOKS_ERROR,
};
